#!/usr/bin/env perl

use strict;
use warnings FATAL => 'all';
use Mojolicious::Commands;

use FindBin;
use lib "$FindBin::Bin/../lib";

Mojolicious::Commands->start_app('ojo::ServeDir::App', 'daemon', @ARGV);
